### ISSUE TITLE
no operation provided:)

### ISSUE THREAD

**Issue by sfz009900** [vxcontrol/pentagi#24]
My.env configuration is as follows:
```
## LLM Providers
OPEN_AI_KEY=keyxxxxxxxxxxxxxxxxxxxxx
OPEN_AI_SERVER_URL=https://api.openai.com/v1

ANTHROPIC_API_KEY=
ANTHROPIC_SERVER_URL=https://api.openai.com/v1

## Custom LLM provider
LLM_SERVER_URL=https://api.deepseek.com
LLM_SERVER_KEY=xxxxxxxxxxxxxxx
LLM_SERVER_MODEL=deepseek-chat
LLM_SERVER_CONFIG_PATH=/opt/pentagi/conf/deepseek.provider.yml
```

Then my docker-compose.yml configuration is as follows:
```
  pentagi:
    image: vxcontrol/pentagi:latest
    restart: unless-stopped
    container_name: pentagi
    hostname: pentagi
    expose:
      - 8443/tcp
    ports:
      - 127.0.0.1:8443:8443
    depends_on:
      - pgvector
    environment:
      - DOCKER_GID=998
      - CORS_ORIGINS=${CORS_ORIGINS:-}
      - COOKIE_SIGNING_SALT=${COOKIE_SIGNING_SALT:-}
      - OPEN_AI_KEY=${OPEN_AI_KEY:-}
      - OPEN_AI_SERVER_URL=${OPEN_AI_SERVER_URL:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - ANTHROPIC_SERVER_URL=${ANTHROPIC_SERVER_URL:-}
      - LLM_SERVER_URL=${LLM_SERVER_URL:-}
      - LLM_SERVER_KEY=${LLM_SERVER_KEY:-}
      - LLM_SERVER_MODEL=${LLM_SERVER_MODEL:-}
      - LLM_SERVER_CONFIG_PATH=${LLM_SERVER_CONFIG_PATH:-}
      - PROXY_URL=${PROXY_URL:-}
      - SCRAPER_PUBLIC_URL=${SCRAPER_PUBLIC_URL:-}
      - SCRAPER_PRIVATE_URL=${SCRAPER_PRIVATE_URL:-}
      - PUBLIC_URL=${PUBLIC_URL:-}
      - STATIC_DIR=${STATIC_DIR:-}
      - STATIC_URL=${STATIC_URL:-}
      - SERVER_PORT=${SERVER_PORT:-8443}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_SSL_CRT=${SERVER_SSL_CRT:-}
      - SERVER_SSL_KEY=${SERVER_SSL_KEY:-}
      - SERVER_USE_SSL=${SERVER_USE_SSL:-true}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID:-}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET:-}
      - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID:-}
      - OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET:-}
      - DATABASE_URL=postgres://${PENTAGI_POSTGRES_USER:-postgres}:${PENTAGI_POSTGRES_PASSWORD:-postgres}@pgvector:5432/${PENTAGI_POSTGRES_DB:-pentagidb}?sslmode=disable
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GOOGLE_CX_KEY=${GOOGLE_CX_KEY:-}
      - TRAVERSAAL_API_KEY=${TRAVERSAAL_API_KEY:-}
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-}
      - PERPLEXITY_MODEL=${PERPLEXITY_MODEL:-sonar}
      - PERPLEXITY_CONTEXT_SIZE=${PERPLEXITY_CONTEXT_SIZE:-low}
      - LANGFUSE_BASE_URL=${LANGFUSE_BASE_URL:-}
      - LANGFUSE_PROJECT_ID=${LANGFUSE_PROJECT_ID:-}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-}
      - OTEL_HOST=${OTEL_HOST:-}
      - DOCKER_HOST=${DOCKER_HOST:-unix:///var/run/docker.sock}
      - DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY:-}
      - DOCKER_CERT_PATH=${DOCKER_CERT_PATH:-}
      - DOCKER_INSIDE=${DOCKER_INSIDE:-false}
      - DOCKER_SOCKET=${DOCKER_SOCKET:-}
      - DOCKER_NETWORK=${DOCKER_NETWORK:-}
      - DOCKER_PUBLIC_IP=${DOCKER_PUBLIC_IP:-}
      - DOCKER_WORK_DIR=${DOCKER_WORK_DIR:-}
      - DOCKER_DEFAULT_IMAGE=${DOCKER_DEFAULT_IMAGE:-}
    logging:
      options:
        max-size: 50m
        max-file: '7'
    volumes:
      - pentagi-data:/opt/pentagi/data
      - pentagi-ssl:/opt/pentagi/ssl
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deepseek.provider.yml:/opt/pentagi/conf/deepseek.provider.yml
    user: root:root # while using docker.sock
```

Then my docker - compose. Yml configuration as follows but return visit https://localhost:8443/api/v1/graphql:`{"errors":[{"message":"no operation provided","extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}`
